
spring-mirai:
  # name-config: defaultBeanNameConfig
  bean-name:
    # 在这里可以进行bean替换
    testBean: test2
    # key: name
  config:
    commonDeviceFilePath: device.json




server:
  port: 13000

# token
token:
  privateKey: 'fdasfgdsagaxgsregdfdjyghjfhebfdgwe45ygrfbsdfshfdsag'
  yangToken: 1000000
  oldToken: 3000000000