
spring-mirai:
  #name-config: defaultBeanNameConfig
  bean-name:
    # key: name

spring:
  datasource:
    name: bot
    url: jdbc:mysql://49.235.33.223:3306/mirai?useUnicode=true&characterEncoding=utf-8
    username: mirai
    password: SpringMiraiBot66..
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 13000